<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<!-- <link href="normalize.css"  rel="stylesheet" media="all" type="text/css"> -->
	<link href="styles.css" rel="stylesheet" media="all" type="text/css"> 
	<script src="http://tinymce.cachefly.net/4.1/tinymce.min.js"></script>
	<script>tinymce.init({selector:'textarea'});</script>

	<title>Write Entry</title>
	
	<!--

	<style>
	p.serif {
	    font-family: "Times New Roman", Times, serif;
	}

	p.sansserif {
	    font-family: Arial, Helvetica, sans-serif;
	}
	</style>

	-->

</head>

<header>


</header>

<body>
	
<h1>Ajouter un Article</h1>

<?php $categories = $post_manager ->getCategory(); ?>


<div class="page">		

	<form name="newcontent" method="post" enctype="multipart/form-data" action="addPost.php">

		<fieldset>
			<legend>Créer un article</legend>			

			<p>
				<label for="subject-id">Subject</label>
				<input type="text" name ="subject" id="subject-id">
			</p>

			<p>
				<label for="category">Category</label>

					<select name="category">

					<?php foreach ($categories as $key => $value): ?> 
								
						<option value="<?= $value['id']; ?>"><?= $value['name']; ?></option>
								
					<?php endforeach; ?>

							
					</select>
			</p>

			<p>Inclure une photo : <input type="file" name ="picture" id="upload-id"></p>

			<p>
				<label for="Content">Content</label>
				<textarea name="content" rows="10" cols="40" id="content" value="content">content</textarea>
			<P>

			<p><input type="text" name ="tags" id="tags-id">Tags separate by ,</p>

			<p><input type="submit" name="connexion" value="Publier"></p>

		</fieldset>

	</form>
</div>

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//localhost/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//localhost/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->