<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="styles.css" rel="stylesheet" media="all" type="text/css">
    <title>mini blog</title>
    
</head>


<body>

<header>

<h1>Another PHP Blog </h1>

</header>


			<form action="member.php" name="connexion" method="post">
			
			<fieldset>
				
				<legend>Connexion à l'espace membre :</legend>			

				<p>
					<label for="nom-id">Email</label>
					<input type="text" name ="email" id="email-id" placeholder ="votre email">
				</p>
				
				<p>
					<label for="password-id">Mot de passe : </label>
					<input type="password" name="pass" value="<?php if (isset($_POST['pass'])) echo htmlentities(trim($_POST['pass'])); ?>">
				</p>

				<p>
					<input type="submit" name="connexion" value="Connexion">
				</p>

			</fieldset>

			</form>


<footer>

</footer>
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//localhost/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//localhost/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
</body>