<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="styles.css" rel="stylesheet" media="all" type="text/css">


    <title>mini blog</title>
    
</head>


<body>


<header>
<h1><a href ="/blog/">Another PHP Blog </a></h1>
</header>

<div class="main" class="clearfix">

		<section class="content">
			
			<article>
			<?php $post_manager = new Model_Post(); ?>

				<p class="billet">billet numéro : <?= $post["id"]?>  crée le <?= $post["date_create"] ?> 

					<?php $author = $post_manager ->getAuthor($post["author_id"]); ?>

					Posted by : <?= $author['firstname'].' '.$author['lastname'] ?></p>

					
				<p class="title">Titre: <a href ="post.php?id=<?= $post["id"]?>" class="titre"><?=$post["title"]?></a></p>

				<!-- Test si photo ajouté à un billet -->

						<?php if($post["photo"]):?>

							<div>
								
							<center><img src=images/<?= $post["photo"] ?> width="500" height="500"></center>

							</div>

											
						<?php endif;?>


				<!-- Affichage du contenu du billet -->


				<div id='content'>
						<p><?= $post["content"] ?></p>
				</div>

				<!-- affichage des Tags -->

				<div class="tag">

					<?php $tags = $post_manager ->getTags($post["id"]); ?>



					<?php if(!$tags==""):?>

							<p class="tags">Tags :

								<?php foreach($tags as $tag): ?>

									<?= $tag["tag"];?>

								<?php endforeach; ?>
							</p>
					
					<?php endif;?>

				</div>

				<!-- commentaire à gérer -->

				<div id='comment'>

					<?php $nbcomments = $post_manager ->gettotalComments($post["id"]); ?>

					<!-- <p>Comments [ <?= $nbcomments; ?> ]</p> -->
					<p>Comments [<a href ="post.php?id=<?= $post["id"]?>#display_comments"> <?= $nbcomments; ?></a> ]</p>
					
				</div>


				<!-- si admin possibilitée de supprimer delPost ou modifier UpdatePost le post -->

				<?php if(isset($_SESSION["ISADMIN"]) && ($_SESSION["ISADMIN"])==1):?>

				
				<p><a onclick="return confirm('etes vous sur ?')" href="delpost.php?id=<?= $post["id"]?>">Effacer le billet</a>
				<a href="updatePost.php?id=<?= $post["id"]?>">Modifier le billet</a></p>

					
				<?php endif;?>



			</article>

				<!-- si connecté possibilitée d'ajouter un comment -->

				<?php if(isset($_SESSION["ID"])):?>

						<?php include "comment.phtml"; ?>

				
				<?php else:?>

				<p>Vous devez etre connecté pour pouvoir publier des commentaires</p>

				<?php endif;?>


				<!-- affichage des commentaires -->
				
				<div id="display_comments">

						
						<?php $nbcomments = $post_manager ->getComments($post["id"]); ?>

						<?php foreach ($nbcomments as $comment): ?>

								<?php $author_id = $comment["author_id"];?>

								<?php $author = $post_manager ->getAuthor($author_id); ?>

							<p>commentaire de <?= $author["firstname"].'  '.$author["lastname"]; ?>
							   publié le <?= $comment["date_comment"];?></p>

							<div id="style_comment">
								<p><?= $comment["comment"];?><p>
							</div>
										
						<?php endforeach; ?>


				</div>

				
		</section>

		<section class="menu">

			<nav>

				<?php if(isset($_SESSION["ID"])):?>

				<h4>Members aera</h4>

				<p><a>Welcome </a><strong><?= $_SESSION["NAME"]; ?></strong></p>

				<p><a href="logout.php">Se déconnecter</a></p>


					<?php if(($_SESSION["ISADMIN"])==1):?>

						<div class="box_admin">
								<h2>Admin aera</h2>

								<p><a href="admin.php">Ajouter un article</a></p>
						</div>
					
					<?php endif;?>

					

				<?php else:?>

					<p><a href="login.php">Login</a></p>

				<?php endif;?>


				<h2>Menu</h2>
				<ul>
					<li><a href="/blog/">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<h4>Categorie</h4>
				<h4>Archives</h4>
				<h4>Search</h4>
			</nav>

		</section>

</div>




<footer>

</footer>

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//localhost/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//localhost/piwik/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->


</body>
