<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<!-- <link href="normalize.css"  rel="stylesheet" media="all" type="text/css"> -->
	<link href="styles.css" rel="stylesheet" media="all" type="text/css"> 
	<script src="http://tinymce.cachefly.net/4.1/tinymce.min.js"></script>
	<script>tinymce.init({selector:'textarea'});</script>

	<title>Inscription</title>
	
	<!--

	<style>
	p.serif {
	    font-family: "Times New Roman", Times, serif;
	}

	p.sansserif {
	    font-family: Arial, Helvetica, sans-serif;
	}
	</style>

	-->

</head>

<header>


</header>

<body>


<form name="newmember" method="post" action="register.php">

		<fieldset>

			<legend>Welcome on register page - enjoy my new home made blog </legend>			

			<p>
				<label for="subject-id">firstname</label>
				<input type="text" name ="firstname" id="firstname-id" placeholder="firstname" required>
			</p>

			<p>
				<label for="subject-id">lastname</label>
				<input type="text" name ="lastname" id="lastname-id" placeholder="lastname" required>
			</p>

			<p>
				<label for="subject-id">email</label>
				<input type="email" name ="email" id="email-id" placeholder="email" required>
			</p>

			

			<p>
				<label for="password-id">Password</label>

				<input type="password" name ="password" id="password-id" required>
			</p>


			<p><input type="submit" name="register" value="Valider mon inscription"></p>



		</fieldset>

	</form>
</div>














<footer>

</footer>

</body>
</html>