<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="styles.css" rel="stylesheet" media="all" type="text/css">
    <title>mini blog</title>
    
</head>


<body>

<header>
<h1><a href ="/blog/">Another PHP Blog </a></h1>
</header>

<div class="main" class="clearfix">

		<section class="content">
			
			<article>
			<?php $post_manager = new Model_Post(); ?>

			<?php foreach ($posts as $post): ?>

				<p class="billet">billet numéro : <?= $post["id"]?>  crée le <?= $post["date_create"] ?> 

					<?php $author = $post_manager ->getAuthor($post["author_id"]); ?>

					Posted by : <?= $author['firstname'].' '.$author['lastname'] ?></p>

					
				<p class="title">Titre: <a href ="post.php?id=<?= $post["id"]?>" class="titre"><?=$post["title"]?></a></p>

				<!-- Test si photo ajouté à un billet -->

						<?php if($post["photo"]):?>

							<div>
								
							<center><img src=images/<?= $post["photo"] ?> width="250" height="250"></center>

							</div>

											
						<?php endif;?>


				<!-- affichage du contenu du post -->

				<div id='content'>
					 <p><?= $post["content"] ?> ....</p>
				</div>

				<!-- commentaire à gérer -->

				<div id='comment'>

					<?php $nbcomments = $post_manager ->gettotalComments($post["id"]); ?>


					<p><a href ="post.php?id=<?= $post["id"]?>">Lire la suite</a> |
					Commentaires [<a href ="post.php?id=<?= $post["id"]?>#display_comments"> <?= $nbcomments; ?></a> ]</p>

				</div>


				<!-- si admin possibilitée de supprimer delPost ou modifier UpdatePost le post -->

				<?php if(isset($_SESSION["ISADMIN"]) && ($_SESSION["ISADMIN"])==1):?>

				
						<p><a onclick="return confirm('etes vous sur ?')" href="delpost.php?id=<?= $post["id"]?>">Effacer le billet</a>
						<a href="updatePost.php?id=<?= $post["id"]?>">Modifier le billet</a></p>

					
				<?php endif;?>


			<?php endforeach; ?>

			<!-- Pagination des articles par page -->

					<div class="page">

						<?php if($page>1):?>

							<a href="?page=<?= $page-1;?>">Billets suivant </a>
						
						<?php endif;?>

						<?php if($page<$nbpage):?>
		
							<a href="?page=<?= $page+1;?>">Billets précédent</a>

						<?php endif;?>

					</div>

			</article>

		</section>

		<section class="menu">

			<nav>
				
				

				<?php if(isset($_SESSION["ID"])):?>

				<h4>Members aera</h4>

				<p><a>Welcome </a><strong><?= $_SESSION["NAME"]; ?></strong></p>

				<p><a href="logout.php">Se déconnecter</a></p>


					<?php if(($_SESSION["ISADMIN"])==1):?>

						<div class="box_admin">
								<h2>Admin aera</h2>

								<p><a href="admin.php">Ajouter un article</a></p>
						</div>
					
					<?php endif;?>

					

				<?php else:?>

					<p><a href="login.php">Login</a></p>

				<?php endif;?>
				

				<h2>Menu</h2>

				<ul>
					<li><a href="/blog/">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>

				<h2>Categorie</h2>
				<h2>Archives</h2>
				<h2>Search</h2>

			</nav>

		</section>

</div>




<footer>

</footer>

</body>