<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="styles.css" rel="stylesheet" media="all" type="text/css">
    <title>mini blog</title>
    
</head>


<body>

<header>
<h1>Another PHP Blog </h1>
</header>

<div class="main" class="clearfix">

		<section class="content">
			
			<article>
			<?php $author_id = new Model_Post(); ?>

			<?php foreach ($posts as $post): ?>

				<p class="billet">billet numéro : <?= $post["id"]?>  crée le <?= $post["date_create"] ?> 

					<?php $author = $author_id ->getAuthor($post["author_id"]); ?>

					Posted by : <?= $author['firstname'].' '.$author['lastname'] ?></p>

					
				<p class="title">Titre: <a href ="post.php?id=<?= $post["id"]?>" class="titre"><?=$post["title"]?></a></p>

				<div id='content'>
					 <p><?= $post["content"] ?> ....</p>
				</div>

				<!-- commentaire à gérer -->

				<div id='comment'>

					<?php $nbcomments = $author_id ->gettotalComments($post["id"]); ?>

					<p>Comments [ <?= $nbcomments; ?> ]</p>
					
				</div>


				<!-- si admin possibilitée de supprimer delPost ou modifier UpdatePost le post -->

				<?php if(isset($_SESSION["ISADMIN"]) && ($_SESSION["ISADMIN"])==1):?>

				
						<p><a onclick="return confirm('etes vous sur ?')" href="delpost.php?id=<?= $post["id"]?>">Effacer le billet</a>
						<a href="#">Modifier le billet</a></p>

					
				<?php endif;?>


			<?php endforeach; ?>

			<!-- Pagination des articles par page -->

					<div class="page">

						<?php if($page>1):?>

							<a href="?page=<?= $page-1;?>">Billets précédent </a>
						
						<?php endif;?>

						<?php if($page<$nbpage):?>
		
							<a href="?page=<?= $page+1;?>">Billets suivant</a>

						<?php endif;?>

					</div>

			</article>

		</section>

		<section class="menu">

			<nav>
				
				<h2>Admin aera</h2>

				<?php if(isset($_SESSION["ID"])):?>

				<p><a>Welcome </a><strong><?= $_SESSION["NAME"]; ?></strong></p>

					<?php if(($_SESSION["ISADMIN"])==1):?>

						<p><a href="admin.php">Créer un Billet</a></p>
					
					<?php endif;?>
				

					<p><a href="logout.php">Se déconnecter</a></p>

				<?php else:?>

					<p><a href="login.php">Login</a></p>

				<?php endif;?>
				

				<h2>Menu</h2>

				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>

				<h2>Categorie</h2>
				<h2>Archives</h2>
				<h2>Search</h2>

			</nav>

		</section>

</div>




<footer>

</footer>

</body>