<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<!-- <link href="normalize.css"  rel="stylesheet" media="all" type="text/css"> -->
	<link href="styles.css" rel="stylesheet" media="all" type="text/css"> 
	<script src="http://tinymce.cachefly.net/4.1/tinymce.min.js"></script>
	<script>tinymce.init({selector:'textarea'});</script>

	<title>Update post</title>
	
</head>

<header>


</header>

<body>
	
<h1>modifier cet article</h1>

<?php $categories = $post_manager ->getCategory(); ?>

<div class="page">		

	<form name="modify_comment" method="post" enctype="multipart/form-data" action="updatePost.php">

		<fieldset>
		<legend>update</legend>			

		<p>
			<label for="subject-id">Subject</label>
			<input type="text" name ="subject" id="subject-id" value='<?= $post["title"];?>'>

		</p>



		<p>
			<label for="category">Category</label>

				<select name="category">

				<?php foreach ($categories as $key => $value): ?> 

					<?php if($value['id'] == $post['cat_id']): ?>
					
						<option selected value="<?= $value['id']; ?>"><?= $value['name']; ?></option>

					<?php else: ?>

						<option value="<?= $value['id']; ?>"><?= $value['name']; ?></option>

					<?php endif;?>

							
					
							
				<?php endforeach; ?>

						
				</select>
		</p>


		<?php if($post["photo"]):?>

			<div>
				
			<center><img src=images/<?= $post["photo"] ?> width="250" height="250"></center>

			</div>

							
		<?php endif;?>

		<p>modifier photo : <input type="file" name ="picture" id="upload-id" ></p>
    

        <p><input type="checkbox" name ="delpic">Effacer photo</p>
		

		<p>
		<label for="Content">Content</label>
		<textarea name="content" rows="10" cols="40" id="content"><?= $post["content"];?></textarea>
		</p>


		<input type="hidden" name="id" value='<?= $post["id"];?>'>

		
		<?php $post_manager = new Model_Post(); ?>
		<?php $tags = $post_manager ->getTags($post["id"]); ?>
		
		<?php $tabi=array();?>

		<?php foreach($tags as $tag): ?>

				<?php $tabi[]=$tag["tag"];?>


		<?php endforeach; ?>
		
		<?php $tabi=implode(",",$tabi);?>

		<p><input type="text" name ="tags" id="tags-id" value='<?= $tabi;?>'>Tags separate by ,</p>
		
			<!-- value='<?= $post["tags"];?>' -->

		<p><input type="submit" name="connexion" value="Publier"></p>

		</fieldset>

	</form>
</div>